-- =========================
-- Default kit templates seed
-- =========================
-- Seeds public kit templates (same set as TemplateSeedService defaultTemplates).
-- Run after 000_consolidated_schema.sql and 001_seed_supply_catalog.sql.
-- Uses supply names from 001 to resolve supply_id. Skips any supply not in catalog.

WITH tpls AS (
  INSERT INTO kit_templates (
    user_id, name, description, purpose, group_size, environment, skill_level,
    is_public, default_people_count, people_count_options, created_by, is_active, requires_premium,
    created_at, updated_at
  )
  VALUES
    (NULL, 'Basic First Aid Kit', 'A comprehensive first aid kit for general use at home, work, or on the go. Includes essential supplies for treating minor injuries and emergencies.', 'general', 4, 'indoor', 'beginner', true, 4, ARRAY[1, 2], 'system', true, false, NOW(), NOW()),
    (NULL, 'Hiking/Outdoor Kit', 'Designed for outdoor adventures and hiking trips. Includes supplies for treating injuries in remote locations and handling outdoor-specific emergencies, including advanced trauma care.', 'hiking', 6, 'outdoor', 'intermediate', true, 6, ARRAY[1, 2, 4], 'system', true, false, NOW(), NOW()),
    (NULL, 'Car Emergency Kit', 'Essential first aid supplies to keep in your vehicle. Perfect for roadside emergencies and travel-related injuries.', 'automotive', 5, 'outdoor', 'beginner', true, 5, ARRAY[1, 2, 4], 'system', true, false, NOW(), NOW()),
    (NULL, 'Home Emergency Kit', 'Comprehensive first aid kit for your home. Includes supplies for common household injuries and emergencies for the whole family.', 'home', 8, 'indoor', 'beginner', true, 8, ARRAY[1, 2, 4, 6], 'system', true, false, NOW(), NOW()),
    (NULL, 'Workplace First Aid Kit', 'OSHA-compliant first aid kit designed for workplaces. Suitable for offices, warehouses, and other work environments. Includes comprehensive supplies for workplace injuries.', 'workplace', 20, 'indoor', 'beginner', true, 20, ARRAY[1, 2, 4, 6, 8, 12], 'system', true, false, NOW(), NOW()),
    (NULL, 'Sports/Activity Kit', 'Specialized first aid kit for sports activities, team events, and athletic competitions. Includes supplies for common sports injuries and athletic training needs.', 'sports', 10, 'outdoor', 'intermediate', true, 10, ARRAY[1, 2, 4, 6, 8], 'system', true, false, NOW(), NOW()),
    (NULL, 'Athletic Trainer Kit', 'Comprehensive athletic training kit for sports medicine professionals. Includes specialized supplies for injury prevention, treatment, and rehabilitation for athletes and teams.', 'athletic-training', 18, 'outdoor', 'advanced', true, 18, ARRAY[1, 2, 4, 6, 8, 12], 'system', true, false, NOW(), NOW()),
    (NULL, 'Advanced Medical/EMT Kit', 'Professional-grade medical kit for EMTs, paramedics, and advanced medical responders. Includes advanced trauma care, airway management, monitoring equipment, and IV supplies.', 'advanced-medical', 1, 'any', 'advanced', true, 1, ARRAY[]::integer[], 'system', true, false, NOW(), NOW()),
    (NULL, 'Travel First Aid Kit', 'Compact, portable first aid kit designed for travel. Includes essential supplies in travel-friendly quantities for treating minor injuries while on the go.', 'travel', 3, 'travel', 'beginner', true, 3, ARRAY[1, 2], 'system', true, false, NOW(), NOW())
  RETURNING id, name
),
revs AS (
  INSERT INTO kit_template_revisions (kit_template_id, version, created_at)
  SELECT id, 1, NOW() FROM tpls
  RETURNING id, kit_template_id
)
INSERT INTO kit_template_revision_items (template_revision_id, supply_id, required_units, created_at, updated_at)
SELECT r.id, s.id, v.qty, NOW(), NOW()
FROM (VALUES
  ('Basic First Aid Kit', 'Adhesive Bandages - Assorted Sizes', 20),
  ('Basic First Aid Kit', 'Gauze Pads', 10),
  ('Basic First Aid Kit', 'Sterile Gauze Pads 4x4', 5),
  ('Basic First Aid Kit', 'Medical Tape', 1),
  ('Basic First Aid Kit', 'Antiseptic Wipes', 10),
  ('Basic First Aid Kit', 'Tweezers', 1),
  ('Basic First Aid Kit', 'Scissors', 1),
  ('Basic First Aid Kit', 'Disposable Gloves', 4),
  ('Basic First Aid Kit', 'Antibiotic Ointment', 1),
  ('Basic First Aid Kit', 'Pain Relievers', 1),
  ('Hiking/Outdoor Kit', 'Adhesive Bandages', 30),
  ('Hiking/Outdoor Kit', 'Gauze Pads', 15),
  ('Hiking/Outdoor Kit', 'Sterile Gauze Pads 4x4', 10),
  ('Hiking/Outdoor Kit', 'Medical Tape', 2),
  ('Hiking/Outdoor Kit', 'Antiseptic Wipes', 20),
  ('Hiking/Outdoor Kit', 'Tweezers', 1),
  ('Hiking/Outdoor Kit', 'Scissors', 1),
  ('Hiking/Outdoor Kit', 'Disposable Gloves', 6),
  ('Hiking/Outdoor Kit', 'Moleskin', 1),
  ('Hiking/Outdoor Kit', 'Emergency Blanket', 1),
  ('Hiking/Outdoor Kit', 'Tourniquet', 1),
  ('Hiking/Outdoor Kit', 'QuikClot®', 1),
  ('Hiking/Outdoor Kit', 'Israeli Bandage', 1),
  ('Hiking/Outdoor Kit', 'Compressed Gauze', 2),
  ('Hiking/Outdoor Kit', 'SAM Splint', 1),
  ('Hiking/Outdoor Kit', 'Pain Relievers', 1),
  ('Hiking/Outdoor Kit', 'Antihistamine', 1),
  ('Car Emergency Kit', 'Adhesive Bandages', 25),
  ('Car Emergency Kit', 'Gauze Pads', 12),
  ('Car Emergency Kit', 'Medical Tape', 1),
  ('Car Emergency Kit', 'Antiseptic Wipes', 15),
  ('Car Emergency Kit', 'Tweezers', 1),
  ('Car Emergency Kit', 'Scissors', 1),
  ('Car Emergency Kit', 'Disposable Gloves', 5),
  ('Car Emergency Kit', 'Emergency Blanket', 1),
  ('Car Emergency Kit', 'Flashlight', 1),
  ('Car Emergency Kit', 'Pain Relievers', 1),
  ('Home Emergency Kit', 'Adhesive Bandages', 50),
  ('Home Emergency Kit', 'Gauze Pads', 20),
  ('Home Emergency Kit', 'Medical Tape', 2),
  ('Home Emergency Kit', 'Antiseptic Wipes', 25),
  ('Home Emergency Kit', 'Tweezers', 1),
  ('Home Emergency Kit', 'Scissors', 1),
  ('Home Emergency Kit', 'Disposable Gloves', 10),
  ('Home Emergency Kit', 'Thermometer', 1),
  ('Home Emergency Kit', 'Pain Relievers', 1),
  ('Home Emergency Kit', 'Antihistamine', 1),
  ('Home Emergency Kit', 'Hydrogen Peroxide', 1),
  ('Workplace First Aid Kit', 'Adhesive Bandages - Assorted Sizes', 100),
  ('Workplace First Aid Kit', 'Gauze Pads', 40),
  ('Workplace First Aid Kit', 'Sterile Gauze Pads 4x4', 20),
  ('Workplace First Aid Kit', 'Medical Tape', 4),
  ('Workplace First Aid Kit', 'Antiseptic Wipes', 50),
  ('Workplace First Aid Kit', 'Tweezers', 2),
  ('Workplace First Aid Kit', 'Scissors', 2),
  ('Workplace First Aid Kit', 'Disposable Gloves', 20),
  ('Workplace First Aid Kit', 'Eye Wash Solution', 1),
  ('Workplace First Aid Kit', 'Burn Gel', 1),
  ('Workplace First Aid Kit', 'Antibiotic Ointment', 2),
  ('Workplace First Aid Kit', 'Pain Relievers', 1),
  ('Workplace First Aid Kit', 'CPR Face Shield', 1),
  ('Workplace First Aid Kit', 'Triangular Bandage', 2),
  ('Sports/Activity Kit', 'Adhesive Bandages', 40),
  ('Sports/Activity Kit', 'Gauze Pads', 20),
  ('Sports/Activity Kit', 'Medical Tape', 3),
  ('Sports/Activity Kit', 'Antiseptic Wipes', 30),
  ('Sports/Activity Kit', 'Tweezers', 1),
  ('Sports/Activity Kit', 'Scissors', 1),
  ('Sports/Activity Kit', 'Disposable Gloves', 10),
  ('Sports/Activity Kit', 'Ice Pack', 2),
  ('Sports/Activity Kit', 'Elastic Bandage', 2),
  ('Sports/Activity Kit', 'Athletic Tape', 2),
  ('Sports/Activity Kit', 'Pre-wrap', 2),
  ('Sports/Activity Kit', 'Kinesiology Tape', 1),
  ('Sports/Activity Kit', 'Compression Bandage', 2),
  ('Sports/Activity Kit', 'Biofreeze', 1),
  ('Sports/Activity Kit', 'Icy Hot', 1),
  ('Sports/Activity Kit', 'Pain Relievers', 1),
  ('Sports/Activity Kit', 'Antihistamine', 1),
  ('Athletic Trainer Kit', 'Athletic Tape', 6),
  ('Athletic Trainer Kit', 'Pre-wrap', 6),
  ('Athletic Trainer Kit', 'Kinesiology Tape', 3),
  ('Athletic Trainer Kit', 'Sports Tape', 2),
  ('Athletic Trainer Kit', 'Foam Padding', 4),
  ('Athletic Trainer Kit', 'Heel and Lace Pads', 2),
  ('Athletic Trainer Kit', 'Athletic Trainer Scissors', 2),
  ('Athletic Trainer Kit', 'Ankle Brace', 2),
  ('Athletic Trainer Kit', 'Knee Brace', 2),
  ('Athletic Trainer Kit', 'Wrist Brace', 2),
  ('Athletic Trainer Kit', 'Elbow Brace', 1),
  ('Athletic Trainer Kit', 'Shoulder Brace', 1),
  ('Athletic Trainer Kit', 'Compression Sleeve', 3),
  ('Athletic Trainer Kit', 'Biofreeze', 2),
  ('Athletic Trainer Kit', 'Icy Hot', 2),
  ('Athletic Trainer Kit', 'Tiger Balm', 1),
  ('Athletic Trainer Kit', 'Instant Cold Pack', 6),
  ('Athletic Trainer Kit', 'Compression Bandage', 4),
  ('Athletic Trainer Kit', 'Elastic Bandage', 4),
  ('Athletic Trainer Kit', 'Sterile Gauze Pads 4x4', 20),
  ('Athletic Trainer Kit', 'Sterile Gauze Pads 2x2', 10),
  ('Athletic Trainer Kit', 'Antiseptic Wipes', 40),
  ('Athletic Trainer Kit', 'Disposable Gloves', 20),
  ('Athletic Trainer Kit', 'Cohesive Bandage (Coban)', 4),
  ('Athletic Trainer Kit', 'Pain Relievers', 1),
  ('Advanced Medical/EMT Kit', 'Tourniquet', 2),
  ('Advanced Medical/EMT Kit', 'CAT Tourniquet', 1),
  ('Advanced Medical/EMT Kit', 'Chest Seal', 2),
  ('Advanced Medical/EMT Kit', 'Hemostatic Gauze', 2),
  ('Advanced Medical/EMT Kit', 'QuikClot®', 2),
  ('Advanced Medical/EMT Kit', 'QuikClot® Combat Gauze LE', 1),
  ('Advanced Medical/EMT Kit', 'Israeli Bandage', 2),
  ('Advanced Medical/EMT Kit', 'Compressed Gauze', 4),
  ('Advanced Medical/EMT Kit', 'Abdominal Pad (ABD Pad)', 2),
  ('Advanced Medical/EMT Kit', 'Nasal Airway', 2),
  ('Advanced Medical/EMT Kit', 'Oral Airway', 2),
  ('Advanced Medical/EMT Kit', 'Bag Valve Mask', 1),
  ('Advanced Medical/EMT Kit', 'Stethoscope', 1),
  ('Advanced Medical/EMT Kit', 'Pulse Oximeter', 1),
  ('Advanced Medical/EMT Kit', 'Blood Pressure Cuff', 1),
  ('Advanced Medical/EMT Kit', 'Penlight', 1),
  ('Advanced Medical/EMT Kit', 'IV Catheter', 4),
  ('Advanced Medical/EMT Kit', 'IV Administration Set', 2),
  ('Advanced Medical/EMT Kit', 'Syringe', 6),
  ('Advanced Medical/EMT Kit', 'Needle', 6),
  ('Advanced Medical/EMT Kit', 'Alcohol Prep Pad', 20),
  ('Advanced Medical/EMT Kit', 'Hemostat Curved 5.5"', 1),
  ('Advanced Medical/EMT Kit', 'Hemostat Straight 5.5"', 1),
  ('Advanced Medical/EMT Kit', 'Surgical Scalpel Blade', 2),
  ('Advanced Medical/EMT Kit', 'Suture Removal Kit', 1),
  ('Advanced Medical/EMT Kit', 'Tongue Depressor', 10),
  ('Advanced Medical/EMT Kit', 'Cotton Swabs', 2),
  ('Advanced Medical/EMT Kit', 'Irrigation Syringe', 2),
  ('Advanced Medical/EMT Kit', 'XShear Trauma Shears', 1),
  ('Advanced Medical/EMT Kit', 'N95 Respirator', 5),
  ('Advanced Medical/EMT Kit', 'Gown', 2),
  ('Advanced Medical/EMT Kit', 'Disposable Gloves', 20),
  ('Advanced Medical/EMT Kit', 'Saline Solution', 2),
  ('Advanced Medical/EMT Kit', 'Povidone-Iodine Solution', 1),
  ('Travel First Aid Kit', 'Adhesive Bandages - Assorted Sizes', 15),
  ('Travel First Aid Kit', 'Sterile Gauze Pads 4x4', 5),
  ('Travel First Aid Kit', 'Medical Tape', 1),
  ('Travel First Aid Kit', 'Antiseptic Wipes', 10),
  ('Travel First Aid Kit', 'Tweezers', 1),
  ('Travel First Aid Kit', 'Scissors', 1),
  ('Travel First Aid Kit', 'Disposable Gloves', 2),
  ('Travel First Aid Kit', 'Antibiotic Ointment', 1),
  ('Travel First Aid Kit', 'Pain Relievers', 1),
  ('Travel First Aid Kit', 'Antihistamine', 1),
  ('Travel First Aid Kit', 'First Aid Guide', 1),
  ('Travel First Aid Kit', 'Thermometer', 1)
) AS v(tpl_name, supply_name, qty)
JOIN tpls t ON t.name = v.tpl_name
JOIN revs r ON r.kit_template_id = t.id
CROSS JOIN LATERAL (SELECT id FROM supplies WHERE name = v.supply_name AND scope = 'global' LIMIT 1) s;
