#!/bin/bash
# Script to help maintain Postman collection
# Run this after making API changes

echo "=========================================="
echo "Postman Collection Maintenance Checklist"
echo "=========================================="
echo ""
echo "1. Review git diff for controller changes"
echo "   git diff api/src/**/*.controller.ts"
echo ""
echo "2. Update Postman collection if endpoints changed"
echo "   - Add new endpoints to EverRedi-API.postman_collection.json"
echo "   - Update existing endpoints if method/URL/body changed"
echo "   - Remove deleted endpoints"
echo ""
echo "3. Update environment variables if needed"
echo "   - Check EverRedi-Environments.postman_environment.json"
echo "   - Add new variables if required"
echo ""
echo "4. Run Postman collection tests"
echo "   - Import collection into Postman"
echo "   - Run collection runner"
echo "   - Or use Newman CLI: newman run EverRedi-API.postman_collection.json"
echo ""
echo "5. Update API documentation"
echo "   - Update README.md if endpoint behavior changed"
echo "   - Update collection descriptions"
echo ""
echo "6. Commit changes"
echo "   git add api/postman/"
echo "   git commit -m 'Update Postman collection for API changes'"
echo ""
echo "=========================================="

